### ISSUE TITLE
Speed up simulateMultipleFights

### ISSUE THREAD

**Issue by pie3636** [Diceycle/C-Hero-Calc#19]
Once any solution has been found, it becomes useless to simulate any fights where the line-up's follower cost is above the cheapest found solution's, they can be removed from `armies` or simply ignored.

This would speed up that phase of the computation, I believe.

**Comment by pie3636** [comment]
Sample implementation (to be checked), this can be done simply by moving the follower check before the fight simulation:

```cpp
void simulateMultipleFights(vector<Army> & armies, Instance & instance) {
    bool newFound = false;
    size_t i = 0;
    size_t armyAmount = armies.size();

    for (i = 0; i < armyAmount; i++) {
        if (armies[i].followerCost < instance.followerUpperBound) {
            simulateFight(armies[i], instance.target);
            if (!armies[i].lastFightData.rightWon) {  // left (our side) wins:
                if (!newFound) {
                    iomanager.suspendTimedOutputs(DETAILED_OUTPUT);
                }
                newFound = true;
                instance.followerUpperBound = armies[i].followerCost;
                instance.bestSolution = armies[i];
                iomanager.outputMessage(instance.bestSolution.toString(), DETAILED_OUTPUT, 2);
            }
        }
    }
    if (newFound) {
        iomanager.resumeTimedOutputs(DETAILED_OUTPUT);
    }
}
```

Another, possibly faster possibility is to sort armies by followerCost beforehand and use `std::upper_bound` to skip large parts of the vector at once.

**Comment by pie3636** [comment]
This would probably be worth creating a second, standalone issue, but there is also no need to keep checking once the program has found a 0-follower cost solution.

**Comment by Diceycle** [comment]
This was a good suggestion. I thought the additional check before would somehow outweight the fights that you would skip

Oh, how wrong I was.
