### ISSUE TITLE
Draw fight is considered a solution

### ISSUE THREAD

**Issue by smart0eddie** [Diceycle/C-Hero-Calc#20]
![2017-12-03 18 55 09](https://user-images.githubusercontent.com/4142838/33524625-81cffe6a-d85b-11e7-8293-413c7932968f.png)
sometimes a draw is consider a solution
as shown above

![2017-12-03 18 55 38](https://user-images.githubusercontent.com/4142838/33524634-93dead22-d85b-11e7-9926-bbad1b87a3c4.png)
and here is one of the correct answer

I think maybe somewhere in the code that compare the strength of two lineup should use strictly larger '>' instead of larger or equal '>='

**Comment by Diceycle** [comment]
I checked and the fight in the calc as well as the battle replay show that the proposed solution works.
I see no issue here.
