### ISSUE TITLE
Fatal Error returned

### ISSUE THREAD

**Issue by darryl-a-peterson** [Diceycle/C-Hero-Calc#21]
Welcome to Diceycle's PvE Instance Solver!
If you don't know what to do you can type help at any time to get an explanation about the current step.

Enter your Heroes with levels. Press enter after every Hero.
Press enter twice or type done to proceed without inputting additional Heroes.
Enter Hero 1: shygu:37
Enter Hero 2: petry:99
Enter Hero 3: ignitor:99
Enter Hero 4: nicte:99
Enter Hero 5: forestdruid:99
Enter Hero 6: undine:99
Enter Hero 7: veildur:9
Enter Hero 8: tr0n1x:5
Enter Hero 9: atzar:2
Enter Hero 10: rei:4
Enter Hero 11: auri:3
Enter Hero 12: alpha:3
Enter Hero 13: geror:1
Enter Hero 14: athos:2
Enter Hero 15: xarth:9
Enter Hero 16:
Enter Hero 16:
Set a lower follower limit on monsters used: 650000
Set an upper follower limit that you want to use: -1
Enter Enemy Lineup(s): w15,e15,w14,e15,geum:89

Calculating with 24 available Monsters and 15 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4

Best Solution so far:
  [Followers: 7942000 | xarth:9 ignitor:99 e13 nicte:99 e13 shygu:37 <==]
Continue calculation? (y/n): n

Solution for [Followers: 26263000 | geum:89 e15 w14 e15 w15 <==]:
  [Followers: 7942000 | xarth:9 ignitor:99 e13 nicte:99 e13 shygu:37 <==]
  1196551 Fights simulated.
  Total Calculation Time: 0

Battle Replay (Use on Ingame Tournament Page):
eyJ3aW5uZXIiOiJVbmtub3duIiwibGVmdCI6IlNvbHV0aW9uIiwicmlnaHQiOiJJbnN0YW5jZSIsImRhdGUiOjE1MTI5MDA4OTcsInRpdGxlIjoiUHJvcG9zZWQgU29sdXRpb24iLCJzZXR1cCI6Wy00OCwtMzAsNDksLTIxLDQ5LC01NywtNDgsLTMwLDQ5LC0yMSw0OSwtNTcsLTQ4LC0zMCw0OSwtMjEsNDksLTU3LC00OCwtMzAsNDksLTIxLDQ5LC01NywtNDgsLTMwLDQ5LC0yMSw0OSwtNTddLCJzaGVybyI6WzAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsOTksMCwwLDAsMCwwLDAsMCwwLDk5LDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCw5LDAsMCwwLDAsMCwwLDAsMCwzNywwLDAsMCwwLDAsMCwwLDAsMF0sInBsYXllciI6Wy0yOCw1Nyw1NSw1Nyw1OSwtMSwtMjgsNTcsNTUsNTcsNTksLTEsLTI4LDU3LDU1LDU3LDU5LC0xLC0yOCw1Nyw1NSw1Nyw1OSwtMSwtMjgsNTcsNTUsNTcsNTksLTFdLCJwaGVybyI6WzAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCw4OSwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDBdfQ==

Do you want to calculate more lineups? (y/n): y
Enter Enemy Lineup(s): w15,f15,f15,a14,sigrun:98

Calculating with 24 available Monsters and 15 enabled Heroes.
Trying to find solutions greedily...
Starting loop for armies of size 1
  Simulating 24 non-hero Fights...                          Done! (  0 seconds)
  Simulating 15 hero Fights...                              Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 2
  Simulating 501 non-hero Fights...                         Done! (  0 seconds)
  Simulating 930 hero Fights...                             Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 3
  Simulating 8349 non-hero Fights...                        Done! (  0 seconds)
  Simulating 40395 hero Fights...                           Done! (  0 seconds)
  Expanding Lineups by one...                               Done! (  0 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 4
  Simulating 111797 non-hero Fights...                      Done! (  0 seconds)
  Simulating 1427040 hero Fights...
Best Solution so far:
  [Followers: 10388000 | xarth:9 w15 forestdruid:99 w11 w11 shygu:37 <==]
Continue calculation? (y/n): y

Preparing to work on loop for armies of size 5
Currently considering 111797 normal and 1427040 hero armies.
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! (  9 seconds)
  Expanding Lineups by one...                               Done! (  1 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 5
  Simulating 115420 non-hero Fights...                      Done! (  0 seconds)
  Simulating 5420999 hero Fights...                         Done! (  6 seconds)
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! ( 28 seconds)
  Expanding Lineups by one...                               Done! (  2 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 6
  Simulating 65917 non-hero Fights...                       Done! (  0 seconds)
  Simulating 19112620 hero Fights...
    [Followers: 7426000 | w13 w13 ignitor:99 w11 w11 shygu:37 <==]
                                                            Done! ( 16 seconds)

Solution for [Followers: 23895000 | sigrun:98 a14 f15 f15 w15 <==]:
  [Followers: 7426000 | w13 w13 ignitor:99 w11 w11 shygu:37 <==]
  19046867 Fights simulated.
  Total Calculation Time: 63

Battle Replay (Use on Ingame Tournament Page):
eyJ3aW5uZXIiOiJVbmtub3duIiwibGVmdCI6IlNvbHV0aW9uIiwicmlnaHQiOiJJbnN0YW5jZSIsImRhdGUiOjE1MTI5MDEwNDIsInRpdGxlIjoiUHJvcG9zZWQgU29sdXRpb24iLCJzZXR1cCI6WzUxLDUxLC0zMCw0Myw0MywtNTcsNTEsNTEsLTMwLDQzLDQzLC01Nyw1MSw1MSwtMzAsNDMsNDMsLTU3LDUxLDUxLC0zMCw0Myw0MywtNTcsNTEsNTEsLTMwLDQzLDQzLC01N10sInNoZXJvIjpbMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCw5OSwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMzcsMCwwLDAsMCwwLDAsMCwwLDBdLCJwbGF5ZXIiOlstNjEsNTIsNTgsNTgsNTksLTEsLTYxLDUyLDU4LDU4LDU5LC0xLC02MSw1Miw1OCw1OCw1OSwtMSwtNjEsNTIsNTgsNTgsNTksLTEsLTYxLDUyLDU4LDU4LDU5LC0xXSwicGhlcm8iOlswLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsOTgsMCwwLDAsMCwwXX0=

This does not beat the lineup!!!
FATAL ERROR!!! Please comment this output in the Forums!

Do you want to calculate more lineups? (y/n):

**Comment by darryl-a-peterson** [comment]
Another error-

Welcome to Diceycle's PvE Instance Solver!
If you don't know what to do you can type help at any time to get an explanation about the current step.

Enter your Heroes with levels. Press enter after every Hero.
Press enter twice or type done to proceed without inputting additional Heroes.
Enter Hero 1: shygu:40
Enter Hero 2: petry:99
Enter Hero 3: ignitor:99
Enter Hero 4: nicte:99
Enter Hero 5: forestdruid:99
Enter Hero 6: undine:99
Enter Hero 7: veildur:9
Enter Hero 8: tr0n1x:5
Enter Hero 9: atzar:2
Enter Hero 10: rei:4
Enter Hero 11: auri:3
Enter Hero 12: alpha:3
Enter Hero 13: geror:1
Enter Hero 14: athos:2
Enter Hero 15: xarth:9
Enter Hero 16:
Enter Hero 16:
Set a lower follower limit on monsters used: 650000
Set an upper follower limit that you want to use: -1
Enter Enemy Lineup(s): w15,e15,w14,e15,sigrun:77

Calculating with 24 available Monsters and 15 enabled Heroes.
Starting loop for armies of size 1
Starting loop for armies of size 2
Starting loop for armies of size 3
Starting loop for armies of size 4

Best Solution so far:
  [Followers: 12101000 | xarth:9 w14 e13 nicte:99 e13 shygu:40 <==]
Continue calculation? (y/n): y

Preparing to work on loop for armies of size 5
Currently considering 157714 normal and 1593060 hero armies.
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! (  3 seconds)
  Expanding Lineups by one...                               Done! (  1 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 5
  Simulating 176729 non-hero Fights...                      Done! (  0 seconds)
  Simulating 6191882 hero Fights...
    [Followers: 9491000 | w15 shygu:40 tr0n1x:5 nicte:99 a12 <==]
    [Followers: 7451000 | w12 nicte:99 shygu:40 f15 petry:99 <==]
                                                            Done! (  1 seconds)
  Calculating Dominance for non-heroes...                   Done! (  0 seconds)
  Calculating Dominance for heroes...                       Done! ( 10 seconds)
  Expanding Lineups by one...                               Done! (  1 seconds)
  Moving Data...                                            Done! (  0 seconds)
Starting loop for armies of size 6
  Simulating 1552 non-hero Fights...                        Done! (  0 seconds)
  Simulating 10169009 hero Fights...
    [Followers: 4159000 | w14 undine:99 shygu:40 petry:99 forestdruid:99 nicte:99 <==]
    [Followers: 3345000 | w12 nicte:99 shygu:40 forestdruid:99 a10 a10 <==]
                                                            Done! (  1 seconds)

Solution for [Followers: 26263000 | sigrun:77 e15 w14 e15 w15 <==]:
  [Followers: 3345000 | w12 nicte:99 shygu:40 forestdruid:99 a10 a10 <==]
  8009652 Fights simulated.
  Total Calculation Time: 17

Battle Replay (Use on Ingame Tournament Page):
eyJ3aW5uZXIiOiJVbmtub3duIiwibGVmdCI6IlNvbHV0aW9uIiwicmlnaHQiOiJJbnN0YW5jZSIsImRhdGUiOjE1MTMwNzQzMjQsInRpdGxlIjoiUHJvcG9zZWQgU29sdXRpb24iLCJzZXR1cCI6WzQ3LC0yMSwtNTcsLTI5LDM2LDM2LDQ3LC0yMSwtNTcsLTI5LDM2LDM2LDQ3LC0yMSwtNTcsLTI5LDM2LDM2LDQ3LC0yMSwtNTcsLTI5LDM2LDM2LDQ3LC0yMSwtNTcsLTI5LDM2LDM2XSwic2hlcm8iOlswLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDk5LDAsMCwwLDAsMCwwLDAsOTksMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsNDAsMCwwLDAsMCwwLDAsMCwwLDBdLCJwbGF5ZXIiOlstNjEsNTcsNTUsNTcsNTksLTEsLTYxLDU3LDU1LDU3LDU5LC0xLC02MSw1Nyw1NSw1Nyw1OSwtMSwtNjEsNTcsNTUsNTcsNTksLTEsLTYxLDU3LDU1LDU3LDU5LC0xXSwicGhlcm8iOlswLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsNzcsMCwwLDAsMCwwXX0=

This does not beat the lineup!!!
FATAL ERROR!!! Please comment this output in the Forums!

Do you want to calculate more lineups? (y/n):

**Comment by Diceycle** [comment]
There were a few bugs with sigrun's, koldis' and alvitr's ability in a previous version. This is fixed now.
